# objective:

Analyze company performance, profitability, growth and valuation
across industries.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("financial_clean_dataset (2).csv")

In [ ]:
df.head()

,Name,NSE Code,Industry,Sales,Sales preceding 12months,Net profit,Net profit preceding 12months,EBIT,EBIT last year,EBIDT last year,EPS,OPM,NPM last year,Return on capital employed,Market Capitalization,Sales Growth %,Net Profit Growth %,Market Cap to Sales,Market Cap to Net Profit,Profitability Category
0,20 Microns,20MICRONS,Mining / Minerals / Metals,777.49,738.43,56.16,51.80,95.24,95.24,109.59,15.89,13.59,7.39,21.70,792.37,5.289601,8.416988,1.019139,14.109152,Moderate Profitability
1,21st Cent. Mgmt.,21STCENMGM,Finance & Investments,34.92,11.94,32.23,9.93,32.98,32.98,33.02,30.70,94.27,92.30,73.00,73.96,192.462312,224.572004,2.117984,2.294756,High Profitability
2,360 ONE,360ONE,Finance & Investments,2920.91,2245.61,804.21,717.01,1651.99,1651.99,1708.63,22.41,58.37,27.53,14.47,36627.84,30.072007,12.161616,12.539873,45.545119,High Profitability
3,3B Blackbio,__NA__,Healthcare,74.12,69.24,32.10,28.49,44.45,44.45,45.51,38.13,44.50,43.31,20.95,1014.49,7.047949,12.671113,13.687129,31.604050,High Profitability
4,3C IT Solutions,__NA__,Computers - Software - Medium / Small,61.93,NaN,1.14,NaN,3.91,3.91,4.20,31.67,5.17,1.84,25.63,26.50,NaN,NaN,0.427902,23.245614,Low Profitability

# Top Industries by Profit

In [ ]:
industry_profit = (
    df.groupby('Industry')['Net profit']
    .mean()
    .sort_values(ascending=False)
)

industry_profit.head(15)

Industry
Refineries                                 21441.848750
Banks - Public Sector                      12784.144167
Computers - Software - Large               12228.590000
Automobiles - Passenger Cars                8586.670000
Banks - Private Sector                      7040.056786
Automobiles - LCVs / HCVs                   7015.566000
Oil Drilling / Allied Services              6452.591000
Cigarettes                                  5485.490000
Automobiles - Scooters And 3 - Wheelers     3857.655000
Personal Care - Multinational               3184.585000
Power Generation And Supply                 2920.934828
Food - Processing - MNC                     2022.366667
Finance - Term-Lending Institutions         1999.125000
Automobiles - Motorcycles / Mopeds          1907.580000
Transport - Airlines                        1611.624000
Name: Net profit, dtype: float64

# Top Industries by Revenue

In [ ]:
industry_sales = (
    df.groupby('Industry')['Sales']
    .mean()
    .sort_values(ascending=False)
)

industry_sales.head(15)

Industry
Refineries                                 340038.277500
Automobiles - LCVs / HCVs                   98812.122000
Automobiles - Passenger Cars                93652.830000
Banks - Public Sector                       91765.959167
Computers - Software - Large                79280.867778
Oil Drilling / Allied Services              67759.191000
Steel - Large                               47528.945000
Banks - Private Sector                      31720.340714
Automobiles - Scooters And 3 - Wheelers     22698.860000
Cigarettes                                  19190.797500
Automobiles - Motorcycles / Mopeds          18766.184000
Personal Care - Multinational               18577.525000
Power Generation And Supply                 16100.928966
Transport - Airlines                        15577.912000
Telecommunications - Service Provider       14255.683750
Name: Sales, dtype: float64

# Top Growth Industries

In [ ]:
industry_growth = (
    df.groupby('Industry')['Sales Growth %']
    .mean()
    .sort_values(ascending=False)
)

industry_growth.head(15)

Industry
Cables - Power                           34.190911
Photographic And Allied Products         17.685590
Oil Drilling / Allied Services           15.773899
Finance & Investments                    15.228985
Food - Processing - MNC                  13.908614
Trading                                  13.567063
Pumps                                    13.481014
Engineering - Turnkey Services           12.192593
Air-conditioners                         10.719679
Cement - South India                     10.173118
Automobiles - Motorcycles / Mopeds        9.734571
Construction                              9.636241
Computers - Software - Medium / Small     9.389499
Electronics - Consumer                    8.954849
Telecommunications - Equipment            8.329336
Name: Sales Growth %, dtype: float64

# Top Companies by Market Cap

In [ ]:
top_marketcap = (
    df[['Name','Industry','Market Capitalization']]
    .sort_values(
        by='Market Capitalization',
        ascending=False
    )
)

top_marketcap.head(20)

,Name,Industry,Market Capitalization
2820,Reliance Industr,Refineries,2119728.90
3519,TCS,Computers - Software - Large,1430591.79
1379,HDFC Bank,Banks - Private Sector,1290527.77
505,Bharti Airtel,Telecommunications - Service Provider,870289.41
1468,ICICI Bank,Banks - Private Sector,846840.44
3319,St Bk of India,Banks - Public Sector,754263.57
1564,Infosys,Computers - Software - Large,653840.49
1964,Life Insurance,Finance & Investments,629337.26
1411,Hind. Unilever,Personal Care - Multinational,587303.84
1619,ITC,Cigarettes,531724.33
1937,Larsen & Toubro,Engineering - Turnkey Services,483925.91
410,Bajaj Finance,Finance & Investments,440174.50
1376,HCL Technologies,Computers - Software - Large,397891.13
384,Axis Bank,Banks - Private Sector,392497.45
2106,Maruti Suzuki,Automobiles - Passenger Cars,381093.61
3501,Tata Motors,Automobiles - LCVs / HCVs,363478.30
70,Adani Enterp.,Trading,362805.36
3371,Sun Pharma.Inds.,Pharmaceuticals - Indian - Bulk Drugs & Formln,362515.53
2399,NTPC,Power Generation And Supply,360425.10
1869,Kotak Mah. Bank,Banks - Private Sector,358755.66

# executice conclusion

 The analysis reveals a market characterized by strong sector concentration, particularly within energy and financial industries. While energy companies dominate revenue generation, financial institutions demonstrate superior profitability efficiency. Most companies operate with positive margins, although a significant proportion remain loss-making. Market valuation appears closely linked to profitability, but company size alone does not guarantee operational efficiency. Overall, the dataset highlights substantial variation in performance across industries, creating opportunities for benchmarking and strategic financial analysis.